### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-python-library.git`](https://github.com/cisagov/skeleton-python-library.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Review by jsf9k — CHANGES_REQUESTED** [review]
The changes in this PR are great, but please note that the README for this repository was never updated from the skeleton boilerplate.
image

**Comment by dav3r** [comment]
> The changes in this PR are great, but please note that the README for this repository was never updated from the skeleton boilerplate.

I'll write up a quick blurb for this repo.

**Comment by dav3r** [comment]
> > The changes in this PR are great, but please note that the README for this repository was never updated from the skeleton boilerplate.
> 
> I'll write up a quick blurb for this repo.

@jsf9k - Please take a look at https://github.com/cisagov/action-apb-dashboard/pull/4/commits/0e6eda36b409f34e502905b0ec23daddd1ed2771.

**Review by dav3r — APPROVED** [review]
👍

**Comment by jsf9k** [comment]
> @jsf9k - Please take a look at [0e6eda3](https://github.com/cisagov/action-apb-dashboard/commit/0e6eda36b409f34e502905b0ec23daddd1ed2771).

LGTM!

**Review by jsf9k — APPROVED** [review]

**Pull request merged**
